all:

install:
	install -Dm 755 init-headphone ${DESTDIR}/usr/sbin/init-headphone
	install -Dm 755 init-headphone.modules ${DESTDIR}/etc/sysconfig/modules/init-headphone.modules
	install -Dm 755 init-headphone.service ${DESTDIR}/usr/lib/systemd/system/init-headphone.service

